# Generated by Django 4.1.7 on 2023-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qabul_qiluvchi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
