# Generated by Django 4.1.7 on 2023-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_record_qabul_qiluvchi_alter_record_qaytardi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
