# Generated by Django 4.1.7 on 2023-04-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('daraja', models.CharField(choices=[('Boshlangich', 'Boshlangich'), ('Orta', 'Orta'), ('Yuqori', 'Yuqori')], max_length=50)),
                ('ustoz', models.CharField(max_length=70, verbose_name='ism familyasi')),
                ('narx', models.PositiveBigIntegerField()),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_fam', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(null=True)),
                ('sana', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('holat', models.CharField(choices=[('Boshlandi', 'Boshlandi'), ('Korilyapti', 'Korilyapti'), ('Tugadi', 'Tugadi')], max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=120, null=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('baho', models.PositiveSmallIntegerField(null=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.profil')),
            ],
        ),
    ]
